### ISSUE TITLE
skill issue

### ISSUE THREAD

**Issue by MrTheFall** [ProgrammerPeasant/CPU_emulator#1]
![image](https://github.com/ProgrammerPeasant/CPU_emulator/assets/44548000/3761ab84-c78f-46b5-a4f6-94cdd3cb0b34)
😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂

**Comment by ProgrammerPeasant** [comment]
![o1mNSZvfLhQ](https://github.com/ProgrammerPeasant/CPU_emulator/assets/63032909/91e76871-4256-4944-a9ae-2d257f056239)
